### ISSUE TITLE
ModuleNotFoundError: No module named 'urlpath'

### ISSUE THREAD

**Issue by igrangel** [DerwenAI/kglab#100]
After successfully following the instruction for the installation I got, over and over, the following error. I have installed it in a Conda environment.

**Comment by ceteri** [comment]
Thank you very much @igrangel -- and great meeting you at the PyData SoCal meetup.

I've been trying to recreate this, and I'm not sure which dependencies that Conda are picking up.  There's a new release of `kglab` v0.1.7 on PyPi just a few minutes ago, with an attempt to resolve this issue.

So far, `kglab` has support for making Pip installs on top of Conda, although not building Conda packages directly.  We'd run into some issues with attempts at building Conda packages, due to some of the dependencies.  Using the "Pip atop Conda" approach has worked so far, although I'm very **eager** to hear about edge cases, if not!

There's a file called `meta.yaml` that would become part of a potential Conda package build process. Since we weren't using it directly, I had assumed that Conda would ignore it.  However, possibly not.  I've just updated the dependencies described within that file, as part of the v0.1.7 release.

If you do a `pip install -U kglab` update on top of the Conda environment now, does that resolve the issue?

If not, another temporary workaround could be simply `pip install urlpath` explicitly.  That *should* resolve those errors.  FWIW, that `urlpath` library only gets used if you supply a URL as a file path for one of the serialization methods, which is less common.

Also, may I ask about which environment you're using?

  * Py version
  * OS

Many thanks -
Paco

**Comment by igrangel** [comment]
Thank you @ceteri , I think the idea of the library is great and was awesome to see your presentation as well as the term Graph-Based Data Science. 
The previous issue is solved by using the `pip install urlpath`.
After that, I was asked to install other packages, e.g., rdflib, igraph, etc. Which I did, then I had the following issue. 


DeprecationWarning                        Traceback (most recent call last)
<ipython-input-6-0786263c4022> in <module>
----> 1 import kglab
      2 
      3 namespaces = {
      4     "wtm": "http://purl.org/heals/food/",
      5     "ind": "http://purl.org/heals/ingredient/",

c:\[my_path]\knowledge_graph\kglab\kglab\__init__.py in <module>
      1 from .kglab import KnowledgeGraph
      2 
----> 3 from .subg import Subgraph, SubgraphMatrix, SubgraphTensor
      4 
      5 from .topo import Measure, Simplex0, Simplex1

c:\[my_path]\knowledge_graph\kglab\kglab\subg.py in <module>
      9 from kglab.pkg_types import NodeLike, RDF_Node, RDF_Triple
     10 
---> 11 import igraph as ig  # type: ignore
     12 import networkx as nx  # type: ignore
     13 import pyvis.network  # type: ignore

~\.conda\envs\datascience\lib\site-packages\igraph\__init__.py in <module>
      6 __license__ = "MIT"
      7 
----> 8 raise DeprecationWarning("To avoid name collision with the igraph project, "
      9                          "this visualization library has been renamed to "
     10                          "'jgraph'. Please upgrade when convenient.")

DeprecationWarning: To avoid name collision with the igraph project, this visualization library has been renamed to 'jgraph'. Please upgrade when convenient.

It says its a warning, but actually is an error since the kg object is not built.

**Comment by ceteri** [comment]
I should track, which environment you're working in?  This will be important for resolving the `iGraph` error:

- Py version
- OS

Also, what approach do you use for installation, given use of Conda?

- `pip install kglab` atop a Conda base
- Git clone, then use of the `setup.py`
- Git clone, then use of the `requirements.txt`

Installation of [`iGraph`](https://igraph.org/python/doc/igraph-module.html) is problematic. We may need to back out of support for that.

On the one hand, that library provides better algorithms (e.g., *leiden*) plus adapters for several popular serialization formats.  However, their code isn't native Python and their installer is flaky: there's been some name collision with another project on PyPi, and in tests the problems encountered appear to differ widely on different OS.

We'll do a quick point release of `kglab` to make `iGraph` optional –  I >think< there's a simple way to resolve that :)

**Comment by ceteri** [comment]
Just pushed the v0.1.8 release, which removes the `igraph` dependency.
Now you should be able to use:

```
pip install -U kglab
```

Does that resolve the installation issues with `igraph` ?

Thank you @igrangel for working with me on these issues.

**Comment by igrangel** [comment]
Well, now it worked! Thanks @ceteri. Already testing things out.

**Comment by ceteri** [comment]
Wonderful, so glad to hear! :)
