### ISSUE TITLE
APIs SubgraphTensor SubgraphMatrix etc referenced in examples not available in latest pip install

### ISSUE THREAD

**Issue by anindita-Databricks** [DerwenAI/kglab#101]
kglab.Subgraph existts but not kglab.SubgraphTensor required in some examples
Same is true of some other APIs
Could someone advise on how to move forward
thanks!

AttributeError                            Traceback (most recent call last)
<command-2629084> in <module>
     14 }
     15 
---> 16 subgraph = kglab.SubgraphTensor(kg)
     17 pyvis_graph = subgraph.build_pyvis_graph(style=VIS_STYLE)
     18 

AttributeError: module 'kglab' has no attribute 'SubgraphTensor'

**Comment by ceteri** [comment]
Thank you @anindita-Databricks -- good catch!

This should now be fixed in `v0.1.7` which was pushed to PyPi just a few minutes ago.

We had to do a rollback of the previous release, due to some issues in `pandas` on Ubuntu.  The commits for `SubgraphMatrix` hadn't gone into a PyPi release as a result.

After a `pip install -U kglab` update to the library, is that working better now?
